#!/usr/bin/env python3
"""
generate_porutham_seed.py
Generates the 729-row Nakshatra Porutham seed SQL file.
Based on classical Tamil Jothidam — 27 nakshatras × 27 = 729 pairs.
Run: python supabase/seeds/generate_porutham_seed.py > supabase/seeds/nakshatra_porutham.sql
"""

NAKSHATRAS = [
    "Ashwini", "Bharani", "Krittika", "Rohini", "Mrigashira",
    "Ardra", "Punarvasu", "Pushya", "Ashlesha", "Magha",
    "Purva Phalguni", "Uttara Phalguni", "Hasta", "Chitra", "Swati",
    "Vishakha", "Anuradha", "Jyeshtha", "Mula", "Purva Ashadha",
    "Uttara Ashadha", "Shravana", "Dhanishtha", "Shatabhisha",
    "Purva Bhadrapada", "Uttara Bhadrapada", "Revati",
]

# ── Ganam Groups ──────────────────────────────────────────────────────────────
# 0=Deva, 1=Manushya, 2=Rakshasa
GANAM = [
    0, 2, 0, 0, 1, 2, 0, 0, 2, 0,
    1, 0, 0, 2, 0, 2, 0, 2, 2, 1,
    0, 0, 1, 2, 1, 0, 0,
]

# ── Rajju Groups ───────────────────────────────────────────────────────────────
# Rajju dosha: same group = incompatible
RAJJU = [
    0, 1, 2, 3, 4, 0, 1, 2, 3, 4,
    0, 1, 2, 3, 4, 0, 1, 2, 3, 4,
    0, 1, 2, 3, 4, 0, 1,
]

# ── Vedha Pairs ────────────────────────────────────────────────────────────────
# Index pairs that cause Vedha dosha (0-based)
VEDHA_PAIRS = {
    (0, 23), (1, 20), (2, 21), (3, 19), (4, 17),
    (5, 24), (6, 11), (7, 10), (8, 25), (9, 26),
    (12, 15), (13, 22), (14, 16), (18, 20),
}
VEDHA_SET = set()
for a, b in VEDHA_PAIRS:
    VEDHA_SET.add((a, b))
    VEDHA_SET.add((b, a))

# ── Yoni Groups ────────────────────────────────────────────────────────────────
# Same yoni (animal) = compatible; specific enemy pairs = incompatible
YONI = [
    0, 13, 7, 5, 10, 12, 1, 8, 6, 2,
    4, 4, 11, 9, 9, 2, 3, 6, 14, 14,
    8, 5, 3, 1, 10, 12, 11,
]
# Yoni enemy pairs (animal groups that are enemies)
YONI_ENEMIES = {
    (0, 7), (1, 6), (2, 10), (3, 11), (4, 14), (5, 12), (8, 9), (13, 4),
}
YONI_ENEMY_SET = set()
for a, b in YONI_ENEMIES:
    YONI_ENEMY_SET.add((a, b))
    YONI_ENEMY_SET.add((b, a))

# ── Rasi (Zodiac Sign) ─────────────────────────────────────────────────────────
RASI = [
    0, 0, 0, 1, 1, 2, 2, 3, 3, 4,
    4, 5, 5, 6, 6, 6, 7, 7, 8, 8,
    9, 9, 10, 10, 11, 11, 11,
]
# Rasi compatibility: friendly, neutral, or enemy
RASI_FRIENDS = {
    0: {4, 7, 8}, 1: {3, 6, 9}, 2: {5, 8, 10}, 3: {1, 6, 11},
    4: {0, 7, 9}, 5: {2, 8, 10}, 6: {1, 3, 11}, 7: {0, 4, 10},
    8: {0, 2, 5}, 9: {1, 4, 11}, 10: {2, 5, 7}, 11: {3, 6, 9},
}

# ── Stree Dirgham (distance check) ────────────────────────────────────────────
# Girl's star should be at least 7 nakshatras ahead of boy's star
def stree_dirgham(boy: int, girl: int) -> bool:
    dist = (girl - boy) % 27
    return dist >= 7

# ── Varna ──────────────────────────────────────────────────────────────────────
# Boy's varna should be >= girl's varna: Brahmin=3, Kshatriya=2, Vaishya=1, Shudra=0
VARNA = [
    3, 0, 0, 1, 0, 0, 3, 3, 0, 1,
    1, 1, 1, 2, 3, 1, 2, 0, 0, 2,
    1, 2, 0, 0, 3, 3, 3,
]

# ── Mahendram (star count check) ───────────────────────────────────────────────
# Count from girl's star to boy's star; compatible if 4th, 7th, 10th, 13th, 16th, 19th, 22nd, 25th
MAHENDRAM_COUNTS = {4, 7, 10, 13, 16, 19, 22, 25}

def mahendram(boy: int, girl: int) -> bool:
    dist = ((boy - girl) % 27) + 1
    return dist in MAHENDRAM_COUNTS

# ── Dinam (count from boy's star) ─────────────────────────────────────────────
# Count from boy's star to girl's star; reduce to 9. Compatible: 1,3,4,5,7,8,9
DINAM_COMPATIBLE = {1, 3, 4, 5, 7, 8, 9}

def dinam(boy: int, girl: int) -> bool:
    dist = ((girl - boy) % 27) + 1
    reduced = ((dist - 1) % 9) + 1
    return reduced in DINAM_COMPATIBLE

# ── Generate SQL ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("-- Nakshatra Porutham Matrix — 729 rows")
    print("-- Auto-generated by generate_porutham_seed.py")
    print("-- Paste in Supabase SQL Editor or run via psql\n")
    print("INSERT INTO public.nakshatra_porutham_matrix")
    print("  (boy_star_index, girl_star_index, boy_star_name, girl_star_name,")
    print("   dinam, ganam, mahendram, stree_dirgham, yoni, rasi,")
    print("   rajju, vedha, vasya, varna) VALUES")

    rows = []
    for b in range(27):
        for g in range(27):
            bn = NAKSHATRAS[b].replace("'", "''")
            gn = NAKSHATRAS[g].replace("'", "''")

            p_dinam = dinam(b, g)
            p_ganam = GANAM[b] == GANAM[g] or (GANAM[b] == 0 and GANAM[g] == 1) or (GANAM[b] == 1 and GANAM[g] == 0)
            p_mahendram = mahendram(b, g)
            p_stree = stree_dirgham(b, g)
            p_yoni = YONI[b] == YONI[g] or (YONI[b], YONI[g]) not in YONI_ENEMY_SET
            p_rasi = RASI[g] in RASI_FRIENDS.get(RASI[b], set()) or RASI[b] == RASI[g]
            p_rajju = RAJJU[b] != RAJJU[g]
            p_vedha = (b, g) not in VEDHA_SET
            p_vasya = (b % 9) in {(g % 9), (g % 9 + 1) % 9}  # simplified vasya
            p_varna = VARNA[b] >= VARNA[g]

            def tf(v): return "true" if v else "false"

            rows.append(
                f"  ({b}, {g}, '{bn}', '{gn}', "
                f"{tf(p_dinam)}, {tf(p_ganam)}, {tf(p_mahendram)}, {tf(p_stree)}, "
                f"{tf(p_yoni)}, {tf(p_rasi)}, {tf(p_rajju)}, {tf(p_vedha)}, "
                f"{tf(p_vasya)}, {tf(p_varna)})"
            )

    print(",\n".join(rows) + ";")
    print("\n-- Done: 729 rows inserted.")
